"""
==============================================================
HQFSF Feature Importance Visualization

Hybrid Quantum Feature Selection Framework (HQFSF)

Provides visualization of feature importance scores
generated by the quantum feature selection framework.
==============================================================
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


class FeatureImportancePlot:
    """
    Visualize feature importance scores.
    """

    def plot(
        self,
        scores: np.ndarray,
        feature_names: list[str] | None = None,
        title: str = "Quantum Feature Importance",
        xlabel: str = "Features",
        ylabel: str = "Importance Score",
        figsize: tuple[int, int] = (10, 6),
        save_path: str | Path | None = None,
        show: bool = True,
    ) -> None:
        """
        Plot feature importance scores.

        Parameters
        ----------
        scores : np.ndarray
            Importance score for each feature.

        feature_names : list[str] | None, optional
            Feature names. If None, default names (F1, F2, ...)
            are generated.

        title : str, optional
            Plot title.

        xlabel : str, optional
            Label for the x-axis.

        ylabel : str, optional
            Label for the y-axis.

        figsize : tuple[int, int], optional
            Figure size.

        save_path : str | Path | None, optional
            Output image path.

        show : bool, optional
            Whether to display the figure.
        """

        scores = np.asarray(scores)

        if feature_names is None:
            feature_names = [
                f"F{i + 1}"
                for i in range(len(scores))
            ]

        if len(feature_names) != len(scores):
            raise ValueError(
                "feature_names and scores must have the same length."
            )

        fig, ax = plt.subplots(figsize=figsize)

        bars = ax.bar(feature_names, scores)

        ax.set_title(title)
        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)

        ax.grid(
            axis="y",
            linestyle="--",
            alpha=0.4,
        )

        plt.setp(ax.get_xticklabels(), rotation=45, ha="right")

        for bar, value in zip(bars, scores):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                value,
                f"{value:.3f}",
                ha="center",
                va="bottom",
                fontsize=9,
            )

        fig.tight_layout()

        if save_path is not None:
            fig.savefig(
                save_path,
                dpi=300,
                bbox_inches="tight",
            )

        if show:
            plt.show()

        plt.close(fig)

    @staticmethod
    def summary() -> None:
        """
        Display a summary of the visualization.
        """

        print("\n" + "=" * 60)
        print("Feature Importance Plot")
        print("=" * 60)
        print("Visualization : Bar Chart")
        print("Purpose       : Display Feature Importance")
        print("=" * 60)